
language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$
