
language: node_js
sudo: false
node_js:
  - "node"
install:
  - echo 'KEY' >> $HOME/.ssh/known_hosts
  - npm install
addons:
  ssh-keyscan:
  - 104.131.110.212
  - 159.65.39.38
deploy:
  skip_cleanup: true
  provider: script
  before_script:
    - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script: ./deploy.sh $TRAVIS_BRANCH
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^development|master$
